### ISSUE TITLE
File not found: '/home/runner/work/_actions/gagoar/invoke-aws-lambda/master/dist/index.js'

### ISSUE THREAD

**Issue by Barik85** [gagoar/invoke-aws-lambda#183]
We using this action:
```
steps:
      - name: Invoke foobarFunction Lambda
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          InvocationType: 'Event'
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: my-trigger
          Payload: ${{ toJson(github) }}
```

 And it works perfect almost for a year.
      Just right now we got an error: File not found: '/home/runner/work/_actions/gagoar/invoke-aws-lambda/master/dist/index.js'

**Comment by eagerowl** [comment]
Same issue here.

**Comment by JoanAliberti** [comment]
same issue here.

**Comment by franlmnastaiunigo** [comment]
Same one !

**Comment by gagoar** [comment]
please use the release version to make sure is safe.  
```
steps:
      - name: Invoke foobarFunction Lambda
        uses: gagoar/invoke-aws-lambda@v3.3.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          InvocationType: 'Event'
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: my-trigger
          Payload: ${{ toJson(github) }}
```
